- hostname: R1
  enable_secret: cisco
  username: cisco
  secret: cisco
  interfaces:
    - name: GigabitEthernet0/0
      description: Connected to R2 
      switchport: false
      ip: 10.0.0.0
      mask: 255.255.255.0
      enabled: true
      speed: 1000
      duplex: full
    - name: GigabitEthernet0/1
      description: Connected to R2 
      switchport: true
      ip: 10.0.0.0
      mask: 255.255.255.0
      enabled: true
      speed: 1000
      duplex: full
  bgp:
    as: 65534
    router_id: 10.1.1.1
    neighbors:
      - neighbor: 1.1.1.1 
        remote_as: 65534
        description: R2
        next_hop_self: true
        route_map_out: OUT
        route_map_in: IN
      - neighbor: 1.1.1.2
        remote_as: 65534
        description: R2
        next_hop_self: true
        route_map_out: OUT
        route_map_in: IN